---
version: '3'
services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=jerry'
      - 'POSTGRES_PASSWORD=pa55w0rd'
    volumes:
      - postgres12-data:/var/lib/postgresql/data

volumes:
  postgres12-data:
