---
version: '3'
services:
  mysql:
    image: mysql:5
    hostname: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_ROOT_HOST=%"
    volumes:
      - mysql-data:/var/lib/mysql/

volumes:
  zookeeper-data:
  zookeeper-secrets:
  zookeeper-txn-logs:
  kafka-data:
  kafka-secrets:
